### PR TITLE
Fix issue where incorrect bLength descriptors would cause infinite loop.

### LINKED ISSUE #5: Analyzer hangs up (infinite loop) when the bLength of a descriptor is shorter than the actual descriptor length.
Details here:
https://discuss.saleae.com/t/usb-analyzer-how-well-does-it-work/2092

### PR DESCRIPTION
**Pull request by Marcus10110**
Fix #5

### CODE REVIEW

**Comment by Marcus10110** [comment]
In the error condition, the remaining bytes from the

File: src/USBControlTransfers.cpp [hunk 1]
```diff
@@ -1226,9 +1231,21 @@ void USBControlTransferParser::ParseDataPacket( USBPacket& packet )
             else
             {
                 if( mDescType == DT_STRING )
-                    ParseStringDescriptor();
+                {
+                    bool detected_complete_descriptor = ParseStringDescriptor();
+                    if( detected_complete_descriptor && mPacketDataBytes > mPacketOffset )
+                    {
+                        // we finished parsing the complete string descrptor, acording to bLength, however there are still bytes left in the
```
Comment (schmicro) [inline src/USBControlTransfers.cpp]:
```suggestion
                        // we finished parsing the complete string descriptor, according to bLength, however there are still bytes left in the
```

**Review by schmicro — CHANGES_REQUESTED** [review]
